### ISSUE TITLE
Deployment : Code deployment fails 

### ISSUE THREAD

**Issue by raul1991** [ashish-chopra/angular-gauge#11]
Steps to reproduce
================

1. Clone the repo
2. Install node.js
3. Run ``` npm install ```
Nothing happens after that (few dependencies are downloaded though )

Note : It is showing no errors on the console.

## Dev Environment
node - 4.6.0
npm - 2.15.9
cmd - MINGW32

**Comment by ashish-chopra** [comment]
When `npm install` completed. Did you run `gulp` command? This command will build the library code and start the server. and then you can browse the example at http://localhost:3000

**Comment by raul1991** [comment]
Actually it did not complete. It sort of hanged after that.

**Comment by ashish-chopra** [comment]
It seems hanged. But it takes a while to download all the dependencies. Once it completes, it lists all the downloaded modules. The downloading time may depend upon the network speed.

**Comment by raul1991** [comment]
![image](https://cloud.githubusercontent.com/assets/1281636/18986640/55d63924-871b-11e6-98c3-8690361be5a0.png)

**Comment by ashish-chopra** [comment]
Try using normal cmd. Git bash cmd may be giving some issues with npm install procedure.

**Comment by raul1991** [comment]
Started correctly on mac. Have to find a way to run it on MINGW32

**Comment by ashish-chopra** [comment]
I tried it on MINGW64 however, it was working fine. Make sure you get the latest version of npm.

my stack was:
node - 4.1.0
npm - 3.3.4
cmd - MINGW64

**Comment by ashish-chopra** [comment]
I am closing this issue. Since its working on normal cmd window, MINGW64 and mac as reported with above software stack details.
