### ISSUE TITLE
angular-gauge.github.io demo needs to be created

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/angular-gauge#15]

**Comment by babruix** [comment]
Please, add gh-pages branch.
Are there any ideas on how you want this page to look?

**Comment by ashish-chopra** [comment]
gh-pages branch created and settings have been updated to use this branch for project site.

Yeah, I want to keep the greenish theme which is there in the screenshot. I saw one similar theme in automatic site generator too. And i do not want any user interaction for gauges. Just to show some use cases and its corresponding code snippets.

Say, a minimal design.

- Ashish

**Comment by ashish-chopra** [comment]
@babruix thanks for your help. The website is up and running at https://ashish-chopra.github.io/angular-gauge/

Hope you like the library and the website. Keep using it if you can and post your suggestions, issues, feature requests etc.
