### ISSUE TITLE
Angular 2 Version

### ISSUE THREAD

**Issue by leocaseiro** [ashish-chopra/angular-gauge#16]
Hi @ashish-chopra, are you interested in make the same directive as an angular 2 component?

**Comment by ashish-chopra** [comment]
Hi @leocaseiro Yes i am in for it. Would it be good to go in the same repo or should i setup a different repo for it?

**Comment by leocaseiro** [comment]
Hi @ashish-chopra. Perhaps a new repo in TypeScript.

I read real quick your source and I believe there's a lot of JS and CSS, much more than any Angular. I Please correct if I'm wrong, but Angular is just to helping with binding.

With that said, a nice alternative would be refactoring this lib into a JS lib to use without any dependency, so it could have a directive for AngularJS and a Component for Angular2 that uses this JS lib. Perhaps even a React Component and Polymer as well.

I'm happy to collaborate. Let me know your thoughts.

**Comment by ashish-chopra** [comment]
Yes, you are right. I wanted to keep the Gauge as a separate object and let angular talk to it for updations/modifications/notifications only. I do not want to intermix angular specific code with actual gauge code. And one reason was to separate it out into a vanilla JS library. So going by this approach is also cool. Let me know, i will setup the repo for vanilla JS library if needed or we simply do a refactoring in this repo for now and later move it to a seperate repo?

**Comment by leocaseiro** [comment]
Hi @ashish-chopra, it's up to you, which one do you believe better?

Both ways works for me. Perhaps a new branch here would be nice so that old users could see the evolution of the library.

**Comment by sanuradhag** [comment]
Hi @ashish-chopra ,
I can't find the angular 2+ version of this project. Is it published or are you still working on it?
Thanks.

**Comment by ashish-chopra** [comment]
@sanuradhag Yes, i am still working on it. And it will be available on https://github.com/ashish-chopra/ngx-gauge repository.

**Comment by sanuradhag** [comment]
@ashish-chopra okay. great :+1:

**Comment by ashish-chopra** [comment]
Hello Guys, Sorry for late information. ngx-gauge library is live for past few days. You can download and use it for Angular 4 based projects.

Cheers
Ashish
