### ISSUE TITLE
inserting json fetched values to value attribute

### ISSUE THREAD

**Issue by akshayallu64** [ashish-chopra/angular-gauge#18]
how to insert values that are fetched from json to value attribute of ng-guage.

for example:
<p class="level" ng-repeat = "item in leveler">
   	<span>{{item.l1.open}}</span>
  		
  		<div flex layout="row" layout-sm="column" layout-xs="column" layout-md="row">
			<div flex layout="column">
				<div flex class="overdue1">Overdue</div>
				<div flex class="guage1" layout-align="center"><ng-gauge size="100" type="full" thick="8" value="(item.l1.open)" cap="round"  foreground-color="black" background-color="rgba(0,0,0, 0.4)" append="Tickets"></div>
			</div>

**Comment by ashish-chopra** [comment]
Hi @akshayallu64 incase you need to see a working example of the query you asked, check out the new website for the library at https://ashish-chopra.github.io/angular-gauge/ in Demos section.
