### ISSUE TITLE
Is it possible to not redraw from 0?

### ISSUE THREAD

**Issue by rohan-buchner** [ashish-chopra/angular-gauge#21]
When updating a chart value, is it possible to not have the chart redraw from 0 each time?

**Comment by ashish-chopra** [comment]
I had opened the similar issue #3. Can you send a pull request for this issue?

Anyways i think, some change is needed in mathematical equation that calculates the coverage on the arc as well for this issue.

**Comment by ssbrewco** [comment]
First off, nice work on the gauge - hard to find one like yours that plays well with AngularJS.

Anyhow, would like to +1 the request to address the "redraw from 0" issue mentioned above. Would be much easier to redraw (higher or lower) starting from the current value.

Thanks!

**Comment by ashish-chopra** [comment]
Thanks @ssbrewco for your kind words.  Hope if someone can send a pull request to do the required changes.

**Comment by karlmtc** [comment]
I have created #40 with the feature. It updates from the previous value if there's any, or the min value if it hasn't been updated yet, instead of always updating from the min value.

**Comment by ashish-chopra** [comment]
Thanks @karlmtc , its amazing. I will test your pull request soon.

Thanks
Ashish

**Comment by ssbrewco** [comment]
Really looking forward to this one!

**Comment by ashish-chopra** [comment]
#40 merged in the master. I will release it shortly. Thanks!
