### ISSUE TITLE
Github Page

### ISSUE THREAD

**Issue by sahilbabbar** [ashish-chopra/angular-gauge#22]
Hi @ashish-chopra, it would be very helpful if you can add a GitHub page to showcase the demo of this directive. This will serve a quick comparison between other dashboard directives as well.

**Comment by ashish-chopra** [comment]
Hi @sahilbabbar, 

i already had this thing in my backlog and i am working on it. Very soon i will publish the website (may be at the end of this week), in case if you want to contribute in completing website work faster, checkout the gh-pages branch on this repo.

Meanwhile, you can see the working example's snapshots on README or you can simply download the code and dependencies and if you follow contribute section on README, you can host examples bundled with the library on your local machine to fiddle with.

Thanks
Ashish

**Comment by ashish-chopra** [comment]
Hi @sahilbabbar The website is ready to show you some demos of gauge directive. Checkout at 
https://ashish-chopra.github.io/angular-gauge/

Keep raising issues/feature requests etc for gauge directive as required.
