### ISSUE TITLE
change value dynamically

### ISSUE THREAD

**Issue by husamawajan** [ashish-chopra/angular-gauge#23]
thank you for your effort but how can i change the value dynamically ?

**Comment by rohan-buchner** [comment]
@husamawajan Erm... bind to it.

 ```
  <ng-gauge
   type="arch"
   thick="13"
   value="$ctrl.yourValue"
   cap="Static Title"
   foreground-color="#ff9800"
   background-color="rgba(255,255,255,0.3)"
   append="{{$ctrl.someAppend}}">
  </ng-gauge>
```

Then in your controller

```
   SomeService.getData()
   .then(function (data) {
     this.yourValue = data;
   });
```

**Comment by ashish-chopra** [comment]
Hi @husamawajan  checkout in case you need to see a working example of the query you asked, check out the new website for the library at https://ashish-chopra.github.io/angular-gauge/ in Demos section. 

Keep posting your issues/queries/feature requests/suggestions to improve the library.
