### ISSUE TITLE
Text display inside gauge with firefox

### ISSUE THREAD

**Issue by atefBB** [ashish-chopra/angular-gauge#28]
I'm using ng-gauge on firefox (v53.0 (32 bits) Win7), the text inside the gauge is displayed correctly on chrome but with firefox the text is displayed outside the gauge.
my HTML code is:
`<ng-gauge size="150" type="full" thick="5" value="some_data" cap="round" label="text here" foreground-color="#0095c8" background-color="#c8c7cc" duration="1000" append="%"></ng-gauge>`
the displayed gauge here:
![ddd](https://cloud.githubusercontent.com/assets/10966925/25538974/cd3ddf50-2c3c-11e7-9f31-92721cc3b0f5.png)

**Comment by ashish-chopra** [comment]
Hi Atef,

Before getting into the internals of your problem, i tried opening the official website of angular-gauge (https://ashish-chopra.github.io/angular-gauge) in firefox (53.0) win7 and the gauges are rendered perfectly fine. Checkout the screenshot below:

![screenshot-53 0-firefox](https://cloud.githubusercontent.com/assets/1948545/25554749/c74eda66-2cf2-11e7-80cc-2c8c8d43ab34.PNG)

However, i will try to reproduce the problem that you might arrive at, meanwhile just open this site in firefox at your end and confirm the results. If everything is okay, i suspect some CSS is overriding the default CSS of the angular-gauge.

**Comment by atefBB** [comment]
thanks @ashish-chopra!
the gauges are rendered perfectly in the official website! 
but in my 'testing' website they aren't!

**Comment by ashish-chopra** [comment]
Hi @atefBB ,

Which version of angular-gauge library are you using in your project? 
If possible can you share some code like HTML showing ng-gauge wrapped in some parent divs and related CSS?

You can email me the code if it is private/protected - sendtoashishchopra@gmail.com


Regards
Ashish

**Comment by ashish-chopra** [comment]
Hi @atefBB,

I am able to reproduce your problem on `angularjs-gauge v1.1.1`. It seems that it is broken in Firefox. But all the latest versions, 1.2.0 or 1.3.0 is working fine in firefox. Can you please upgrade your installation to new version.

Change the version in package.json to 1.3.0 and  run npm install. To make sure you get the latest, check the package.json file in `node_modules/angularjs-gauge` folder.

Let me know if the problem still persists.

Thanks
Ashish

**Comment by ashish-chopra** [comment]
In your source code of angularjs-gauge.js (or minified), whatever you are using. Change the highlighed code to as mentioned below and then let me know if you experience the same issue again?

![snapshot](https://cloud.githubusercontent.com/assets/1948545/25562425/a2147cea-2da3-11e7-83ea-b125f9614489.PNG)

`display:inline-block;`

Make sure you reload the browser window so that fresh file is downloaded to test.

Cheers
Ashish

**Comment by atefBB** [comment]
Thanks M. Ashish.
I'm not at work, and I'll try your recommendation and see the result soooooon !

**Comment by atefBB** [comment]
Peeeeeeeeeeeerfect! after adding `display:inline-block;` in the `angularjs-gauge.js` file it rendered perfectly now.
Thanks!
![ddd-gauge](https://cloud.githubusercontent.com/assets/10966925/25607799/16a2f678-2f10-11e7-9bd8-0c45a5978d31.png)

**Comment by ashish-chopra** [comment]
Great, @atefBB 

I found that this bug exists in latest version also. I will release 1.3.1 with bug fix shortly.

Thanks
Ashish

**Comment by ashish-chopra** [comment]
Hey @atefBB ,

I have just released the latest version 1.3.1 including the fix. You can update your package.json.

 Cheers
Ashish

**Comment by atefBB** [comment]
Thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanks M. @ashish-chopra !
I'll do (In shaa Allah) !

**Comment by ashish-chopra** [comment]
Shukriya :+1:
