### ISSUE TITLE
Value updates are not shown properly

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/angular-gauge#3]
When the value is updated in the gauge, then instead of showing animation of delta. It redraws the whole gauge again from zero.

**Comment by havanagrawal** [comment]
Hi Ashish, I'd like to work on some of these issues. I've recently learnt Angular and I'm sure I can contribute here.. Please let me know if I can pick up any of these issues 😁

**Comment by ashish-chopra** [comment]
Hi Havana, Glad to see you want to contribute into the repository. Initially just play around with the gauge component, try to use it and test it thoroughly by using it. And if you find some issues which are not already there in the issue tracker then raise it. This way you get used to what has been done so far and the setup process as well. I will come back to you by tomorrow, what else needs to be done so that you can start with the contribution. If you feel comfortable with current issue, you can go ahead with it too. Thanks!

**Comment by ashish-chopra** [comment]
Hi havan,

You can pick any of the following items:

1. I have added the test framework for this library. You can contribute in writing the test cases. Check #5  issue for more details.
2. You can work on adding the "stripe" attribute to the gauge. it will create dashed line like background instead of solid line as shown in the image.

![stripe-gauge](https://cloud.githubusercontent.com/assets/1948545/19083799/5e0e4bea-8a81-11e6-8448-5110e08f1f04.png)

3. Even you can work on this issue itself #3. When we update the value of the gauge let say it was initially 25 and now it becomes 50, then the gauge animation should move from 25 to 50; and if the new value is 15, then gauge animation move from 25 to 15 in backward direction. But what is happening currently, it recreate the gauge every time value updates.

4. You can also try, issue #9 . The value label is showing the hard value 25 and the gauge is animating from 0 - 25 however. What is required, that the label also flickers from 0-25 along with the ongoing animation.

Let me know what you are picking to work upon. Try these issues or any other issues whichever you like.

**Comment by ashish-chopra** [comment]
Not taking up this issue. As deprioritized.
