### ISSUE TITLE
Max Min Values

### ISSUE THREAD

**Issue by onncho** [ashish-chopra/angular-gauge#30]
Hey, 
can i set range of values? 
for example: 1-5 instead of  0-100

**Comment by ashish-chopra** [comment]
No as of now. But i mentioned in issue #29 That i will be launching a major release 2.0 of this gauge next week, then it will have an API like `min`, `max`, `value` which resembles the API pattern of meter element of HTML 5.

**Comment by onncho** [comment]
Awesome! thanks for the fast response.

**Comment by sahilbabbar** [comment]
@ashish-chopra waiting for `v2.0`.

**Comment by ashish-chopra** [comment]
@sahilbabbar, Everything is ready to roll-out. Just fixing the publishing lifecyle of the project.

**Comment by ashish-chopra** [comment]
checkout the latest release https://github.com/ashish-chopra/angular-gauge/releases/tag/v2.0.0
