### ISSUE TITLE
handle 'mouseover' event in gauges

### ISSUE THREAD

**Issue by atefBB** [ashish-chopra/angular-gauge#31]
I'm using the gauge inside a div and when I select the div to handle js `hover` event, the event isnot fired, my HTML code:
```
<div id="selected_gauge_id">
	<div>
    	<button type="button" class="some_class_here" ng-click="doStuff()"></button>
	</div>
	<ng-gauge size="70" type="full" thick="2" value="data_here" cap="round" label="label_here"  foreground-color="#0095c8" background-color="#c8c7cc" duration="1000" append="%"></ng-gauge>
</div>
```

my `angularjs` code:
```
$scope .doStuff = function() {
   angular.element('#selected_gauge_id')
         .hover(function() {
             console.log('In');
         }, function() {
             console.log('Out');
         });
};
```
any ideas?

**Comment by ashish-chopra** [comment]
Well, your issue title says `Clickable` and inside description your are trying to handle `hover`.

However, there are no `hover` event in HTML5 for HTMLElement types. Hover is a state whereas the event is `mouseover`, which is very well working. The correct way of binding to events in angular is using `ng-mouseover` on `<ng-gauge>` or any other element wrapping it. Try to avoid jqLite operations, using angular.element() and keep it only for directives, as per best practices.

```html
<body ng-controller="myController as mc">
    <ng-gauge ng-mouseover="mc.doThis()" thick="10" type="arch" value="20">
    </ng-gauge>
</body>
```

```js
 angular.module('mymodule', ['angularjs-gauge'])
       .controller('myController', function() {
           var vm = this;
            vm.doThis = function() {
             console.log('mouseovered');
             }
      });
```

Check https://docs.angularjs.org/api/ng/directive/ngMouseover

**Comment by atefBB** [comment]
Thx, I don't know that! 
I'll try this approach and see the result!

**Comment by atefBB** [comment]
@ashish-chopra title of issue changed !
It work !
thx for the advise !
