### ISSUE TITLE
Angular ~1.6 compatibility

### ISSUE THREAD

**Issue by steven-gruverman** [ashish-chopra/angular-gauge#42]
Does angular-gauge work with angular ~1.6? Will it soon?

**Comment by ashish-chopra** [comment]
Hi @steven-gruverman ,

I did not test angular-gauge with 1.6 version while developing. I think, v1.6 was developing that time. But you can try it with angular 1.6 and let me know if there is any issue. If you can do this exercise, this would help me to upgrade it promptly.

Else, i will be free around mid December to start looking into it.

Regards
Ashish

**Comment by steven-gruverman** [comment]
Hi Ashish,
Thanks for your reply. I did have a chance to try it with our application – for the features and angularjs-gauge we use there was one small problem that may have had more to do with our css.
Because we are close to a release I don’t have time now to test more or to get it to work – for now we are just going with the Bower dependencies as-is and dealing with the Javascript errors being thrown because other parts of our app have 1.6 as a dependency.
I will let you know if I have a chance to work on this some more and either find issues with 1.6 or not.
Thanks again,
Steve

Steve Gruverman | Application Developer II
IDEXX Laboratories, Inc. | Steven-Gruverman@idexx.com<mailto:Steven-Gruverman@idexx.com>
Phone: + 1 207 556 6981
Mobile: + 1 207 798 2893

**Comment by ssbrewco** [comment]
I've done limited testing on AngularJS 1.6.5 without issues...

-S

**Comment by ashish-chopra** [comment]
I did some testing with angular 1.6 while testing the pull requests. and no issues found.

**Comment by steven-gruverman** [comment]
Great – thanks for doing that and for letting us know!

Steve Gruverman | Application Developer II
IDEXX Laboratories, Inc. | Steven-Gruverman@idexx.com<mailto:Steven-Gruverman@idexx.com>
Phone: + 1 207 556 6981
Mobile: + 1 207 798 2893

**Comment by ashish-chopra** [comment]
verified and released v2.2.0 of gauge library.
