### ISSUE TITLE
HELP: Issues Integrating into Ionic 4

### ISSUE THREAD

**Issue by tingspain** [ashish-chopra/angular-gauge#67]
hello, 

I am new with Angular 7 and Ionic 4. I am trying to use the Angular Gauge within Ionic, but I am not able to make it work. 

Please, could anyone give me a hint?

Thanks in advance

**Comment by ashish-chopra** [comment]
Angular 7 is a typescript based version of angular which is different from Angular 1.x which is Angular JS. This library angular-gauge is made for AngularJS apps only. If you want to use a gauge component with Angular 2+ apps, use https://github.com/ashish-chopra/ngx-gauge library.

**Comment by tingspain** [comment]
@ashish-chopra, yes I found it and I am using it. 
THANK YOU VERY MUCH 1: your fast reply 2: for the work that you have done!
Thanks!!!
